<?php
/**
 * Mediawiki module for XOOPS
 *
 * Integrating the mediawiki into XOOPS system
 *
 * @copyright	The XOOPS project http://www.xoops.org/
 * @license		http://www.fsf.org/copyleft/gpl.html GNU public license
 * @author		Taiwen Jiang (phppp or D.J.) <php_pp@hotmail.com>, Thomas Riccardi (Niluge_KiWi) <kiwiiii@gmail.com>
 * @since		1.58
 * @version		$Id$
 * @package		module
 */
if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;

$modversion['name'] = _MI_MEDIAWIKI_NAME;
$modversion['description'] = _MI_MEDIAWIKI_DESC;
$modversion['version'] = "1.120";
$modversion['credits'] = "MediaWiki DEV (http://wikimedia.org/); A.D.Horse (test, http://www.cctv3g.com)";
$modversion['author'] = "D.J. (phppp, http://xoops.org.cn, http://xoopsforge.com), Niluge_KiWi";
$modversion['license'] = "GPL see LICENSE";
$modversion['image'] = "images/mediawiki.png";
$modversion['dirname'] = "mediawiki";

// status
$modversion['codename'] = "";

$modversion['onInstall'] = 'include/action.module.php';
$modversion['onUpdate'] = 'include/action.module.php';

// Templates
$modversion['templates'][0]['file'] = 'mediawiki_content.html';
$modversion['templates'][0]['description'] = '';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
//$modversion['sqlfile']['mysql'] = "";

$modversion['tables'] = array(
	"mediawiki_archive",
	"mediawiki_categorylinks",
	"mediawiki_externallinks",
	"mediawiki_filearchive",
	"mediawiki_hitcounter",
	"mediawiki_image",
	"mediawiki_imagelinks",
	"mediawiki_interwiki",
	"mediawiki_ipblocks",
	"mediawiki_job",
	"mediawiki_langlinks",
	"mediawiki_logging",
	"mediawiki_math",
	"mediawiki_objectcache",
	"mediawiki_oldimage",
	"mediawiki_page",
	"mediawiki_pagelinks",
	"mediawiki_page_restrictions",
	"mediawiki_protected_titles",
	"mediawiki_querycache",
	"mediawiki_querycachetwo",
	"mediawiki_querycache_info",
	"mediawiki_recentchanges",
	"mediawiki_redirect",
	"mediawiki_revision",
	"mediawiki_searchindex",
	"mediawiki_site_stats",
	"mediawiki_templatelinks",
	"mediawiki_text",
	"mediawiki_trackbacks",
	"mediawiki_transcache",
	"mediawiki_user",
	"mediawiki_user_groups",
	"mediawiki_user_newtalk",
	"mediawiki_watchlist"
	);

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.php";
$modversion['search']['func'] = "mediawiki_search";

// Blocks
$i=0;
$modversion["blocks"] = array();

$i++;
$modversion["blocks"][$i]["file"] = "block.php";
$modversion["blocks"][$i]["name"] = _MI_MEDIAWIKI_BLOCK_RECENTCHANGES;
$modversion["blocks"][$i]["description"] = "";
$modversion["blocks"][$i]["show_func"] = "mediawiki_recentchanges_show";
$modversion["blocks"][$i]["options"] = "10"; // MaxItems
$modversion["blocks"][$i]["edit_func"] = "mediawiki_recentchanges_edit";
$modversion["blocks"][$i]["template"] = "mediawiki_block_recentchanges.html";

$i++;
$modversion["blocks"][$i]["file"] = "block.php";
$modversion["blocks"][$i]["name"] = _MI_MEDIAWIKI_BLOCK_TOP;
$modversion["blocks"][$i]["description"] = "";
$modversion["blocks"][$i]["show_func"] = "mediawiki_top_show";
$modversion["blocks"][$i]["options"] = "10"; // MaxItems
$modversion["blocks"][$i]["edit_func"] = "mediawiki_top_edit";
$modversion["blocks"][$i]["template"] = "mediawiki_block_top.html";

$i++;
$modversion["blocks"][$i]["file"] = "block.php";
$modversion["blocks"][$i]["name"] = _MI_MEDIAWIKI_BLOCK_HOT;
$modversion["blocks"][$i]["description"] = "";
$modversion["blocks"][$i]["show_func"] = "mediawiki_hot_show";
$modversion["blocks"][$i]["options"] = "10"; // MaxItems
$modversion["blocks"][$i]["edit_func"] = "mediawiki_hot_edit";
$modversion["blocks"][$i]["template"] = "mediawiki_block_hot.html";

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasMain'] = 1;

$modversion['hasconfig'] = 1;

$modversion['config'][] = array(
	'name'			=> 'style' ,
	'title'			=> '_MI_MEDIAWIKI_STYLE' ,
	'description'	=> '_MI_MEDIAWIKI_STYLE_DESC' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'int' ,
	'default'		=> 0,
	'options'		=> array("XOOPS"=>1, "mediawiki"=>2, "Selectable"=>0) 
);
?>
